# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
services:
  app:
    image: sentinelbackend
    volumes:
      - /$REPO_DIRECTORY:/$REPO_DIRECTORY
      - /$PLUGINS_DIRECTORY:/$PLUGINS_DIRECTORY
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms1024m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/sentinelBackend
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
volumes:
  mongodb_data:
