package com.snail.sentinel.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StackTraceElementJoularEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStackTraceElementJoularEntityAllPropertiesEquals(
        StackTraceElementJoularEntity expected,
        StackTraceElementJoularEntity actual
    ) {
        assertStackTraceElementJoularEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertStackTraceElementJoularEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStackTraceElementJoularEntityAllUpdatablePropertiesEquals(
        StackTraceElementJoularEntity expected,
        StackTraceElementJoularEntity actual
    ) {
        assertStackTraceElementJoularEntityUpdatableFieldsEquals(expected, actual);
        assertStackTraceElementJoularEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStackTraceElementJoularEntityAutoGeneratedPropertiesEquals(
        StackTraceElementJoularEntity expected,
        StackTraceElementJoularEntity actual
    ) {
        assertThat(expected)
            .as("Verify StackTraceElementJoularEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStackTraceElementJoularEntityUpdatableFieldsEquals(
        StackTraceElementJoularEntity expected,
        StackTraceElementJoularEntity actual
    ) {
        assertThat(expected)
            .as("Verify StackTraceElementJoularEntity relevant properties")
            .satisfies(e -> assertThat(e.getLineNumber()).as("check lineNumber").isEqualTo(actual.getLineNumber()))
            .satisfies(e -> assertThat(e.getConstructorElement()).as("check constructorElement").isEqualTo(actual.getConstructorElement()))
            .satisfies(e -> assertThat(e.getParent()).as("check parent").isEqualTo(actual.getParent()))
            .satisfies(e -> assertThat(e.getAncestors()).as("check ancestors").isEqualTo(actual.getAncestors()))
            .satisfies(e -> assertThat(e.getConsumptionValues()).as("check consumptionValues").isEqualTo(actual.getConsumptionValues()))
            .satisfies(e -> assertThat(e.getCommit()).as("check commit").isEqualTo(actual.getCommit()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStackTraceElementJoularEntityUpdatableRelationshipsEquals(
        StackTraceElementJoularEntity expected,
        StackTraceElementJoularEntity actual
    ) {
        // empty method
    }
}
